### ISSUE TITLE
Half donut chart in section is frozen

### ISSUE THREAD

**Issue by petchill** [wevisdemo/parliament-watch#86]
**Describe the bug**
Half donut chart in section นักการเมือง is frozen 

**To Reproduce**
1. Go to https://parliamentwatch.wevis.info/assemblies/%E0%B8%AA%E0%B8%A0%E0%B8%B2%E0%B8%9C%E0%B8%B9%E0%B9%89%E0%B9%81%E0%B8%97%E0%B8%99%E0%B8%A3%E0%B8%B2%E0%B8%A9%E0%B8%8E%E0%B8%A3-25
2. click angle right icon to change data set
3. see at chart, it will not changed

**Expected behavior**
It should be changed related to data set

**Screenshots**
this is first time
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/9493d7ca-c963-4e5c-94b5-9fcd1d787631">
this is after I change data set
<img width="1470" alt="image" src="https://github.com/user-attachments/assets/ac611c54-2b49-4b74-b5d8-f0af74d74ae3">
you can see chart is frozen even though data in right section is changed.

**Desktop (please complete the following information):**
 - OS: mac 14.5
 - Browser chrome
 - Version 127.0.6533.89

**Comment by Th1nkK1D** [comment]
If I understand correctly, this bug only exists on the dev server (SSR) but not on the staging (SSG).

I think there is some variable, or function in the component that depends on the props but doesn't "reactive" (prefix with`$`) so when we change the page on SSR the value was calculated once since SvelteKit will render only what it thinks necessary, but on SSG it's working fine because it is a full reload on different page.

For anyone who wants to fix this, the solution would be to turn those variable/function that depends on props to be reactive.

**Comment by Th1nkK1D** [comment]
Fixed in #91 but needs some time to be merged to main and deployed.
